### PR TITLE
Ignore anchors on item path comparison

### PR DESCRIPTION
**Pull request by edsonk**

### CODE REVIEW

**Comment by artfuldodger** [comment]
I could see it going either way, but okay. :+1:

**Comment by BenEddy** [comment]
I'm not sure this universally desired behavior. Would it be possible to expose this as a configuration option? 

This could be a gem configuration option: 
```Ruby
# in navigatrix.rb

module Navigatrix
  def self.configure
    yield(configuration)
  end

  def self.configuration
    @configuration ||= OpenStruct.new({
      ignore_anchors: false
    })
  end
end

# initializers/navigatrix.rb

Navigatrix.configure do |config|
  config.ignore_anchors = true
end
```

Or it could be an option passed when rendering a navigation

```Ruby
render_navigation({
  # ...
  item: {
    ignore_anchors: true
  }
})
```

Is `false` the right default?

**Comment by edsonk** [comment]
Is there a use case for not ignoring anchors?

**Comment by jakesutton** [comment]
I don't understand having an anchor in a navigation path.
If the nav path is `/things/#thing1` I would expect only `/things/#thing1` to make it active. 
If the nav path is `/things/` and can buy either `/things/2` or `/things/#thing1` making it active.

**Comment by edsonk** [comment]
I'm not sure what you mean, but neither of those things can happen currently

**Comment by jakesutton** [comment]
Well I may be making the erroneous assumption that anything "under" a navigation path also makes it active in my second example.

if that's not the case, maybe I can see why you'd want anchors in navigation...

**Comment by edsonk** [comment]
Right now, if you just set a nav to a path, it is only active when you are on that exact path. If you add an anchor to the nav path `{ 'Nav Item' => '/some_path#my_anchor' }`, this item cannot ever be active, because we compare the computed nav path, which includes the anchor, to the request env path info, which already strips out anchors and query params. 

So, since there's no way for `current_path` to include anchors/params, that means there's no way for a nav item which links to such path to ever be active.

I can see the benefit of a configuration if we want to make it more robust and able to handle different types of path configurations, but with the current implementation, I don't see a downside to this.

**Comment by BenEddy** [comment]
> since there's no way for current_path to include anchors/params

Sold

**Comment by BenEddy** [comment]
Bumped version

**Pull request merged**
